# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp.
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param a parameter in the distribution
#' @param b parameter in the distribution
#' @return a random sample of size \code{n}
#' @export
NULL

gibbs_RsampleC <- function(N, a, b, n, thin) {
    .Call('_StatComp21034_gibbs_RsampleC', PACKAGE = 'StatComp21034', N, a, b, n, thin)
}

